import OpenAI from "openai";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

export async function callAIService(prompt: string): Promise<string> {
  try {
    const response = await openai.images.generate({
      model: "gpt-image-1", // better for image generation
      prompt,
      size: "1024x1024",
      n: 2,
    });

    if (!response.data || response.data.length === 0) {
      throw new Error("No images were generated by the AI service.");
    }

    const images = response.data.map((img: { url?: string }) => img.url ?? "");

    return JSON.stringify({ images });
  } catch (error) {
    console.error("AI Service call failed:", error);
    throw new Error("AI Service call failed");
  }
}
