
import type { DisplayProduct, Review, Category, User, FlashDeal, HeroCampaign } from './types';

export const mockProducts: DisplayProduct[] = [
  {
    id: '1',
    name: 'Classic Leather Watch',
    description: 'A timeless piece that combines classic design with modern functionality. Features a genuine leather strap and a stainless steel case. Perfect for any occasion, from formal events to casual outings. Water-resistant up to 50 meters.',
    price: 199.99,
    category: 'Accessories',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 4.5,
    reviewCount: 120,
    vendorId: 'VDR001',
    tags: ['watch', 'leather'],
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x400.png', 'https://placehold.co/400x600.png'],
    sku: 'LW-001',
    stock: 25,
    status: 'Live',
  },
  {
    id: '2',
    name: 'Wireless Bluetooth Headphones',
    description: 'Experience immersive sound with these noise-cancelling wireless headphones. Up to 30 hours of battery life on a single charge. Connects seamlessly to all your devices. Includes a carrying case.',
    price: 149.50,
    category: 'Electronics',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 4.8,
    reviewCount: 350,
    vendorId: 'VDR002',
    tags: ['headphones', 'audio'],
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x400.png', 'https://placehold.co/400x600.png'],
    sku: 'HP-202',
    stock: 50,
    status: 'Live',
  },
  {
    id: '3',
    name: 'Organic Cotton T-Shirt',
    description: 'Made from 100% GOTS certified organic cotton, this t-shirt is both comfortable and sustainable. A wardrobe essential with a classic fit. Available in various colors.',
    price: 29.99,
    category: 'Apparel',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 4.2,
    reviewCount: 85,
    vendorId: 'VDR003',
    tags: ['t-shirt', 'organic'],
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x400.png', 'https://placehold.co/400x600.png'],
    sku: 'TS-ORG-M',
    stock: 150,
    status: 'Archived',
  },
  {
    id: '4',
    name: 'Handcrafted Ceramic Mug',
    description: 'Start your day with a beautiful, handcrafted ceramic mug. Each piece is unique, with subtle variations in color and texture. Microwave and dishwasher safe. Holds 12 oz.',
    price: 24.00,
    category: 'Home Goods',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 4.9,
    reviewCount: 215,
    vendorId: 'VDR004',
    tags: ['mug', 'ceramic'],
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x400.png', 'https://placehold.co/400x600.png'],
    sku: 'CM-HND-BL',
    stock: 8,
    status: 'Live',
  },
  {
    id: '5',
    name: 'Gourmet Coffee Beans',
    description: 'A rich and aromatic blend of single-origin Arabica beans from the highlands of Colombia. Medium roast with notes of chocolate and citrus. Whole bean, 12 oz bag.',
    price: 18.99,
    category: 'Groceries',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 4.7,
    reviewCount: 412,
    vendorId: 'VDR005',
    tags: ['coffee', 'beans'],
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x400.png', 'https://placehold.co/400x600.png'],
    sku: 'CB-COL-12',
    stock: 0,
    status: 'Archived',
  },
  {
    id: '6',
    name: 'Professional Yoga Mat',
    description: 'This non-slip, eco-friendly yoga mat provides the perfect cushioning and stability for your practice. Made from natural tree rubber. Includes a carrying strap.',
    price: 79.99,
    category: 'Sports',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 4.6,
    reviewCount: 198,
    vendorId: 'VDR006',
    tags: ['yoga', 'fitness'],
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x400.png', 'https://placehold.co/400x600.png'],
    sku: 'YM-PRO-BLK',
    stock: 35,
    status: 'Needs Review',
  },
  {
    id: '7',
    name: 'Modern Minimalist Desk',
    description: 'A sleek and stylish desk that fits perfectly in any modern workspace. Features a durable oak top and sturdy steel legs. Easy assembly required.',
    price: 349.00,
    category: 'Furniture',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 4.4,
    reviewCount: 55,
    vendorId: 'VDR007',
    tags: ['desk', 'furniture'],
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x400.png', 'https://placehold.co/400x600.png'],
    sku: 'DSK-MIN-OAK',
    stock: 12,
    status: 'Live',
  },
  {
    id: '8',
    name: 'All-Natural Skincare Set',
    description: 'Rejuvenate your skin with this set of all-natural skincare products, including a cleanser, toner, and moisturizer. Vegan and cruelty-free. Suitable for all skin types.',
    price: 89.99,
    category: 'Beauty',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 4.8,
    reviewCount: 289,
    vendorId: 'VDR008',
    tags: ['skincare', 'beauty'],
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x400.png', 'https://placehold.co/400x600.png'],
    sku: 'SKN-SET-NAT',
    stock: 40,
    status: 'Live',
  },
  {
    id: '9',
    name: 'Hand-poured Soy Candle',
    description: 'A beautiful soy wax candle in a reusable glass jar. Lavender and vanilla scent. 40+ hour burn time.',
    price: 22.50,
    category: 'Home Goods',
    imageUrl: 'https://placehold.co/600x600.png',
    rating: 4.9,
    reviewCount: 150,
    vendorId: 'VDR004',
    tags: ['candle', 'home'],
    images: ['https://placehold.co/600x600.png'],
    sku: 'CNDL-SOY-LV',
    stock: 60,
    status: 'Live',
  },
];

export const mockReviews: Review[] = [
    { id: '1', author: 'Jane D.', avatarUrl: 'https://placehold.co/40x40.png', rating: 5, title: 'Absolutely love it!', comment: 'This is the best purchase I have made this year. The quality is outstanding and it looks even better in person.', date: '2024-05-15' },
    { id: '2', author: 'John S.', avatarUrl: 'https://placehold.co/40x40.png', rating: 4, title: 'Pretty good', comment: 'Solid product, works as advertised. The packaging was a bit flimsy but the product itself is great.', date: '2024-05-12' },
    { id: '3', author: 'Emily R.', avatarUrl: 'https://placehold.co/40x40.png', rating: 5, title: 'Exceeded my expectations', comment: 'I was hesitant at first but I am so glad I bought it. Highly recommended!', date: '2024-05-10' },
    { id: '4', author: 'Mike T.', avatarUrl: 'https://placehold.co/40x40.png', rating: 3, title: 'It\'s okay', comment: 'Does the job, but it feels a bit overpriced for what it is. Not bad, but not amazing either.', date: '2024-05-08' },
];

export const mockCategories: Category[] = [
    { name: 'Electronics', imageUrl: 'https://placehold.co/400x300.png', productCount: 150 },
    { name: 'Apparel', imageUrl: 'https://placehold.co/400x300.png', productCount: 320 },
    { name: 'Home Goods', imageUrl: 'https://placehold.co/400x300.png', productCount: 210 },
    { name: 'Books', imageUrl: 'https://placehold.co/400x300.png', productCount: 80 },
    { name: 'Sports', imageUrl: 'https://placehold.co/400x300.png', productCount: 120 },
    { name: 'Beauty', imageUrl: 'https://placehold.co/400x300.png', productCount: 180 },
];

export const mockUsers: User[] = [
    { id: 'USR001', name: 'Olivia Martin', email: 'olivia.martin@email.com', role: 'Customer', status: 'Active', joinedDate: '2024-01-15', avatar: 'https://placehold.co/40x40.png' },
    { id: 'USR002', name: 'Timeless Co.', email: 'contact@timeless.co', role: 'Vendor', status: 'Active', joinedDate: '2024-02-20', avatar: 'https://placehold.co/40x40.png' },
    { id: 'USR003', name: 'Jackson Lee', email: 'jackson.lee@email.com', role: 'Customer', status: 'Active', joinedDate: '2024-03-10', avatar: 'https://placehold.co/40x40.png' },
    { id: 'USR004', name: 'Crafty Creations', email: 'hello@crafty.com', role: 'Vendor', status: 'Suspended', joinedDate: '2024-03-15', avatar: 'https://placehold.co/40x40.png' },
    { id: 'USR005', name: 'Isabella Nguyen', email: 'isabella.nguyen@email.com', role: 'Customer', status: 'Active', joinedDate: '2024-04-05', avatar: 'https://placehold.co/40x40.png' },
    { id: 'USR006', name: 'Gadget Guru', email: 'support@gadgetguru.io', role: 'Vendor', status: 'Active', joinedDate: '2024-04-22', avatar: 'https://placehold.co/40x40.png' },
    { id: 'USR007', name: 'William Kim', email: 'will@email.com', role: 'Customer', status: 'Active', joinedDate: '2024-05-30', avatar: 'https://placehold.co/40x40.png' },
    { id: 'USR008', name: 'HomeBody Decor', email: 'sales@homebody.com', role: 'Vendor', status: 'Active', joinedDate: '2024-06-01', avatar: 'https://placehold.co/40x40.png' },
];

// Mock data for the new marketing features
const futureDate = new Date();
futureDate.setDate(futureDate.getDate() + 3);

export const mockFlashDeals: FlashDeal[] = [
    {
        product: mockProducts[1],
        discountPercentage: 25,
        endDate: futureDate.toISOString(),
        stock: 100,
        sold: 45,
    },
    {
        product: mockProducts[6],
        discountPercentage: 30,
        endDate: futureDate.toISOString(),
        stock: 50,
        sold: 12,
    },
    {
        product: mockProducts[7],
        discountPercentage: 20,
        endDate: futureDate.toISOString(),
        stock: 80,
        sold: 60,
    },
    {
        product: mockProducts[0],
        discountPercentage: 15,
        endDate: futureDate.toISOString(),
        stock: 40,
        sold: 5,
    },
]

export const mockHeroCampaigns: HeroCampaign[] = [
    {
        title: "Summer Collection is Here!",
        description: "Fresh looks for sunny days. Explore our new arrivals in apparel and accessories.",
        link: "/products?category=Apparel",
        cta: "Shop Now",
        imageUrl: "https://placehold.co/1920x1080.png",
        hint: "summer fashion"
    },
    {
        title: "Upgrade Your Workspace",
        description: "Find the perfect gear to boost your productivity. Desks, chairs, and tech gadgets.",
        link: "/products?category=Furniture",
        cta: "Explore Home Office",
        imageUrl: "https://placehold.co/1920x1080.png",
        hint: "modern office"
    },
    {
        title: "Save Big on Electronics",
        description: "Limited-time deals on headphones, smart watches, and more.",
        link: "/products?category=Electronics",
        cta: "View Deals",
        imageUrl: "https://placehold.co/1920x1080.png",
        hint: "tech gadgets"
    }
]
